<?php
/**
 * Modelo Catalogo - Tablas maestras de solo lectura
 * Módulo de Facturación
 *
 * Centraliza el acceso a tablas de catálogo simples para evitar
 * crear un modelo y API por cada tabla maestra.
 */

class Catalogo {
    private Database $db;

    private const WHITELIST = [
        'tipos_cliente' => ['Tipos_Clientes', 'Codigo', 'Codigo', 'Codigo'],
    ];

    private const PAISES = [
        ['id'=>'AD','label'=>'Andorra'],
        ['id'=>'AE','label'=>'Emiratos Árabes Unidos'],
        ['id'=>'AF','label'=>'Afganistán'],
        ['id'=>'AG','label'=>'Antigua y Barbuda'],
        ['id'=>'AL','label'=>'Albania'],
        ['id'=>'AM','label'=>'Armenia'],
        ['id'=>'AO','label'=>'Angola'],
        ['id'=>'AQ','label'=>'Antártida'],
        ['id'=>'AR','label'=>'Argentina'],
        ['id'=>'AS','label'=>'Samoa Americana'],
        ['id'=>'AT','label'=>'Austria'],
        ['id'=>'AU','label'=>'Australia'],
        ['id'=>'AW','label'=>'Aruba'],
        ['id'=>'AZ','label'=>'Azerbaiyán'],
        ['id'=>'BA','label'=>'Bosnia y Herzegovina'],
        ['id'=>'BB','label'=>'Barbados'],
        ['id'=>'BD','label'=>'Bangladés'],
        ['id'=>'BE','label'=>'Bélgica'],
        ['id'=>'BF','label'=>'Burkina Faso'],
        ['id'=>'BG','label'=>'Bulgaria'],
        ['id'=>'BH','label'=>'Baréin'],
        ['id'=>'BI','label'=>'Burundi'],
        ['id'=>'BJ','label'=>'Benín'],
        ['id'=>'BN','label'=>'Brunéi'],
        ['id'=>'BO','label'=>'Bolivia'],
        ['id'=>'BR','label'=>'Brasil'],
        ['id'=>'BS','label'=>'Bahamas'],
        ['id'=>'BT','label'=>'Bután'],
        ['id'=>'BW','label'=>'Botsuana'],
        ['id'=>'BY','label'=>'Bielorrusia'],
        ['id'=>'BZ','label'=>'Belice'],
        ['id'=>'CA','label'=>'Canadá'],
        ['id'=>'CD','label'=>'Congo (Rep. Dem.)'],
        ['id'=>'CF','label'=>'República Centroafricana'],
        ['id'=>'CG','label'=>'Congo'],
        ['id'=>'CH','label'=>'Suiza'],
        ['id'=>'CI','label'=>'Costa de Marfil'],
        ['id'=>'CK','label'=>'Islas Cook'],
        ['id'=>'CL','label'=>'Chile'],
        ['id'=>'CM','label'=>'Camerún'],
        ['id'=>'CN','label'=>'China'],
        ['id'=>'CO','label'=>'Colombia'],
        ['id'=>'CR','label'=>'Costa Rica'],
        ['id'=>'CU','label'=>'Cuba'],
        ['id'=>'CV','label'=>'Cabo Verde'],
        ['id'=>'CW','label'=>'Curazao'],
        ['id'=>'CY','label'=>'Chipre'],
        ['id'=>'CZ','label'=>'República Checa'],
        ['id'=>'DE','label'=>'Alemania'],
        ['id'=>'DJ','label'=>'Yibuti'],
        ['id'=>'DK','label'=>'Dinamarca'],
        ['id'=>'DM','label'=>'Dominica'],
        ['id'=>'DO','label'=>'República Dominicana'],
        ['id'=>'DZ','label'=>'Argelia'],
        ['id'=>'EC','label'=>'Ecuador'],
        ['id'=>'EE','label'=>'Estonia'],
        ['id'=>'EG','label'=>'Egipto'],
        ['id'=>'ER','label'=>'Eritrea'],
        ['id'=>'ES','label'=>'España'],
        ['id'=>'ET','label'=>'Etiopía'],
        ['id'=>'FI','label'=>'Finlandia'],
        ['id'=>'FJ','label'=>'Fiyi'],
        ['id'=>'FK','label'=>'Islas Malvinas'],
        ['id'=>'FM','label'=>'Micronesia'],
        ['id'=>'FO','label'=>'Islas Feroe'],
        ['id'=>'FR','label'=>'Francia'],
        ['id'=>'GA','label'=>'Gabón'],
        ['id'=>'GB','label'=>'Reino Unido'],
        ['id'=>'GD','label'=>'Granada'],
        ['id'=>'GE','label'=>'Georgia'],
        ['id'=>'GF','label'=>'Guayana Francesa'],
        ['id'=>'GG','label'=>'Guernsey'],
        ['id'=>'GH','label'=>'Ghana'],
        ['id'=>'GI','label'=>'Gibraltar'],
        ['id'=>'GL','label'=>'Groenlandia'],
        ['id'=>'GM','label'=>'Gambia'],
        ['id'=>'GN','label'=>'Guinea'],
        ['id'=>'GP','label'=>'Guadalupe'],
        ['id'=>'GQ','label'=>'Guinea Ecuatorial'],
        ['id'=>'GR','label'=>'Grecia'],
        ['id'=>'GT','label'=>'Guatemala'],
        ['id'=>'GU','label'=>'Guam'],
        ['id'=>'GW','label'=>'Guinea-Bisáu'],
        ['id'=>'GY','label'=>'Guyana'],
        ['id'=>'HK','label'=>'Hong Kong'],
        ['id'=>'HN','label'=>'Honduras'],
        ['id'=>'HR','label'=>'Croacia'],
        ['id'=>'HT','label'=>'Haití'],
        ['id'=>'HU','label'=>'Hungría'],
        ['id'=>'ID','label'=>'Indonesia'],
        ['id'=>'IE','label'=>'Irlanda'],
        ['id'=>'IL','label'=>'Israel'],
        ['id'=>'IM','label'=>'Isla de Man'],
        ['id'=>'IN','label'=>'India'],
        ['id'=>'IQ','label'=>'Irak'],
        ['id'=>'IR','label'=>'Irán'],
        ['id'=>'IS','label'=>'Islandia'],
        ['id'=>'IT','label'=>'Italia'],
        ['id'=>'JE','label'=>'Jersey'],
        ['id'=>'JM','label'=>'Jamaica'],
        ['id'=>'JO','label'=>'Jordania'],
        ['id'=>'JP','label'=>'Japón'],
        ['id'=>'KE','label'=>'Kenia'],
        ['id'=>'KG','label'=>'Kirguistán'],
        ['id'=>'KH','label'=>'Camboya'],
        ['id'=>'KI','label'=>'Kiribati'],
        ['id'=>'KM','label'=>'Comoras'],
        ['id'=>'KN','label'=>'San Cristóbal y Nieves'],
        ['id'=>'KP','label'=>'Corea del Norte'],
        ['id'=>'KR','label'=>'Corea del Sur'],
        ['id'=>'KW','label'=>'Kuwait'],
        ['id'=>'KY','label'=>'Islas Caimán'],
        ['id'=>'KZ','label'=>'Kazajistán'],
        ['id'=>'LA','label'=>'Laos'],
        ['id'=>'LB','label'=>'Líbano'],
        ['id'=>'LC','label'=>'Santa Lucía'],
        ['id'=>'LI','label'=>'Liechtenstein'],
        ['id'=>'LK','label'=>'Sri Lanka'],
        ['id'=>'LR','label'=>'Liberia'],
        ['id'=>'LS','label'=>'Lesoto'],
        ['id'=>'LT','label'=>'Lituania'],
        ['id'=>'LU','label'=>'Luxemburgo'],
        ['id'=>'LV','label'=>'Letonia'],
        ['id'=>'LY','label'=>'Libia'],
        ['id'=>'MA','label'=>'Marruecos'],
        ['id'=>'MC','label'=>'Mónaco'],
        ['id'=>'MD','label'=>'Moldavia'],
        ['id'=>'ME','label'=>'Montenegro'],
        ['id'=>'MG','label'=>'Madagascar'],
        ['id'=>'MH','label'=>'Islas Marshall'],
        ['id'=>'MK','label'=>'Macedonia del Norte'],
        ['id'=>'ML','label'=>'Malí'],
        ['id'=>'MM','label'=>'Myanmar'],
        ['id'=>'MN','label'=>'Mongolia'],
        ['id'=>'MO','label'=>'Macao'],
        ['id'=>'MP','label'=>'Islas Marianas del Norte'],
        ['id'=>'MQ','label'=>'Martinica'],
        ['id'=>'MR','label'=>'Mauritania'],
        ['id'=>'MT','label'=>'Malta'],
        ['id'=>'MU','label'=>'Mauricio'],
        ['id'=>'MV','label'=>'Maldivas'],
        ['id'=>'MW','label'=>'Malaui'],
        ['id'=>'MX','label'=>'México'],
        ['id'=>'MY','label'=>'Malasia'],
        ['id'=>'MZ','label'=>'Mozambique'],
        ['id'=>'NA','label'=>'Namibia'],
        ['id'=>'NC','label'=>'Nueva Caledonia'],
        ['id'=>'NE','label'=>'Níger'],
        ['id'=>'NF','label'=>'Isla Norfolk'],
        ['id'=>'NG','label'=>'Nigeria'],
        ['id'=>'NI','label'=>'Nicaragua'],
        ['id'=>'NL','label'=>'Países Bajos'],
        ['id'=>'NO','label'=>'Noruega'],
        ['id'=>'NP','label'=>'Nepal'],
        ['id'=>'NR','label'=>'Nauru'],
        ['id'=>'NZ','label'=>'Nueva Zelanda'],
        ['id'=>'OM','label'=>'Omán'],
        ['id'=>'PA','label'=>'Panamá'],
        ['id'=>'PE','label'=>'Perú'],
        ['id'=>'PF','label'=>'Polinesia Francesa'],
        ['id'=>'PG','label'=>'Papúa Nueva Guinea'],
        ['id'=>'PH','label'=>'Filipinas'],
        ['id'=>'PK','label'=>'Pakistán'],
        ['id'=>'PL','label'=>'Polonia'],
        ['id'=>'PM','label'=>'San Pedro y Miquelón'],
        ['id'=>'PN','label'=>'Pitcairn'],
        ['id'=>'PR','label'=>'Puerto Rico'],
        ['id'=>'PS','label'=>'Palestina'],
        ['id'=>'PT','label'=>'Portugal'],
        ['id'=>'PW','label'=>'Palaos'],
        ['id'=>'PY','label'=>'Paraguay'],
        ['id'=>'QA','label'=>'Catar'],
        ['id'=>'RE','label'=>'Reunión'],
        ['id'=>'RO','label'=>'Rumanía'],
        ['id'=>'RS','label'=>'Serbia'],
        ['id'=>'RU','label'=>'Rusia'],
        ['id'=>'RW','label'=>'Ruanda'],
        ['id'=>'SA','label'=>'Arabia Saudita'],
        ['id'=>'SB','label'=>'Islas Salomón'],
        ['id'=>'SC','label'=>'Seychelles'],
        ['id'=>'SD','label'=>'Sudán'],
        ['id'=>'SE','label'=>'Suecia'],
        ['id'=>'SG','label'=>'Singapur'],
        ['id'=>'SI','label'=>'Eslovenia'],
        ['id'=>'SK','label'=>'Eslovaquia'],
        ['id'=>'SL','label'=>'Sierra Leona'],
        ['id'=>'SM','label'=>'San Marino'],
        ['id'=>'SN','label'=>'Senegal'],
        ['id'=>'SO','label'=>'Somalia'],
        ['id'=>'SR','label'=>'Surinam'],
        ['id'=>'SS','label'=>'Sudán del Sur'],
        ['id'=>'ST','label'=>'Santo Tomé y Príncipe'],
        ['id'=>'SV','label'=>'El Salvador'],
        ['id'=>'SX','label'=>'Sint Maarten'],
        ['id'=>'SZ','label'=>'Esuatini'],
        ['id'=>'TC','label'=>'Islas Turcas y Caicos'],
        ['id'=>'TD','label'=>'Chad'],
        ['id'=>'TG','label'=>'Togo'],
        ['id'=>'TH','label'=>'Tailandia'],
        ['id'=>'TJ','label'=>'Tayikistán'],
        ['id'=>'TL','label'=>'Timor Oriental'],
        ['id'=>'TM','label'=>'Turkmenistán'],
        ['id'=>'TN','label'=>'Túnez'],
        ['id'=>'TO','label'=>'Tonga'],
        ['id'=>'TR','label'=>'Turquía'],
        ['id'=>'TT','label'=>'Trinidad y Tobago'],
        ['id'=>'TV','label'=>'Tuvalu'],
        ['id'=>'TW','label'=>'Taiwán'],
        ['id'=>'TZ','label'=>'Tanzania'],
        ['id'=>'UA','label'=>'Ucrania'],
        ['id'=>'UG','label'=>'Uganda'],
        ['id'=>'US','label'=>'Estados Unidos'],
        ['id'=>'UY','label'=>'Uruguay'],
        ['id'=>'UZ','label'=>'Uzbekistán'],
        ['id'=>'VA','label'=>'Ciudad del Vaticano'],
        ['id'=>'VC','label'=>'San Vicente y las Granadinas'],
        ['id'=>'VE','label'=>'Venezuela'],
        ['id'=>'VG','label'=>'Islas Vírgenes Británicas'],
        ['id'=>'VI','label'=>'Islas Vírgenes EE.UU.'],
        ['id'=>'VN','label'=>'Vietnam'],
        ['id'=>'VU','label'=>'Vanuatu'],
        ['id'=>'WF','label'=>'Wallis y Futuna'],
        ['id'=>'WS','label'=>'Samoa'],
        ['id'=>'XK','label'=>'Kosovo'],
        ['id'=>'YE','label'=>'Yemen'],
        ['id'=>'YT','label'=>'Mayotte'],
        ['id'=>'ZA','label'=>'Sudáfrica'],
        ['id'=>'ZM','label'=>'Zambia'],
        ['id'=>'ZW','label'=>'Zimbabue'],
    ];

    public function __construct() {
        $this->db = Database::getInstance();
    }

    public function esValido(string $clave): bool {
        return $clave === 'paises' || isset(self::WHITELIST[$clave]);
    }

    public function todos(string $clave): array {
        if ($clave === 'paises') {
            return self::PAISES;
        }

        [$tabla, $colId, $colLabel, $orden] = self::WHITELIST[$clave];

        return $this->db->fetchAll(
            "SELECT `{$colId}` AS id, `{$colLabel}` AS label
             FROM `{$tabla}`
             ORDER BY `{$orden}`"
        );
    }
}
